#!/bin/sh

myip=$(/sbin/ifconfig eth0 | sed -n 's/ *inet [^0-9]*\([0-9\.]\+\).*/\1/p')
iprange=${myip%.*}.*
nmap -sn $iprange | grep -Eo '([0-9][0-9.]+$)' | grep -v "^$myip$" > $HOME/hostiplist
for i in $(<$HOME/hostiplist); do ssh $i hostname; done > $HOME/hostfile

sshin=$(wc -l < $HOME/hostfile)
ipcount=$(wc -l < $HOME/hostiplist)

if [ $sshin -eq $ipcount ]; then
  status="OK"
else
  status="KO"
fi

echo "status=$status;hosts=$ipcount;sshin=$sshin"
